# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c",om
# ********************************************************************
import os

Import('env')

cflags = ''

source = []

current = Dir('.').srcnode().path

if os.path.exists('config.mak'):
    print 'configure is up-to-date'
else:
    env.Command('config.mak', 'configure', 'cd %s && ./configure CC=%s CROSS_COMPILE=%s CFLAGS=-Wno-error=pointer-sign' %
                (current, env['CC'], env['CC_PREFIX']))
env.Command('libmusl',
            'Makefile',
            'cd %s && make -j8 && cp lib/libc.a lib/libmusl.a' % (current))
