# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c",om
# ********************************************************************
import os
import SCons

Import('env')

cflags = ''

source = []

current = Dir('.').srcnode().path


params = [env['CC'],
          'CROSS_COMPILE='+env['CC_PREFIX'],
          'CFLAGS=-g -Wno-error=pointer-sign -DSYSCALL_NO_TLS %s ' % (
    env['CFLAGS']),
    '--disable-optimize',
    '--enable-debug=yes',
    '--enable-shared=yes'
]

configured = env.AutoConfig(Dir('.'),
                            AutoConfigParams=params,
                            AutoConfigTarget=['config.mak'],
                            AutoConfigSource='configure'
                            )


musl = env.Make(
    MakePath=Dir('.'),
    source=[
        'config.mak',
        'Makefile'
    ],
    target=['libm.a',
            'libc.a',
            'bits/alltypes.h'
            ],
)

musl = env.Command(
    'libmusl.a',
    ['libc.a',
     'libm.a',
     ],
    'cd %s && cp lib/libc.a lib/libmusl.a && cp lib/libc.so lib/libmusl2.so' % (current))


env.Clean('musl',
          ['config.mak',
           Glob('./**/**.[o|a]'),
           'obj',
           'lib'])

Return('musl')
