# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

cflags='-Iapp/libcmocka/include \
        -I. \
        '

source=[]

source+=Glob('src/*.c')

source +=[
    ]

libs=[]

env.Library('cmocka', source,
    LIBS=libs+env.get('LIBS'),
    CFLAGS='$CFLAGS $LIBCFLAGS -DBSD -D__YIYIYA__ -DHAVE_SIGNAL_H  '+cflags,
    LINKFLAGS= '$LINKFLAGS $USER')