# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cliEnv')
env=cliEnv.Clone()


env.AddInclude([
    '#eggs/libcmocka/include',
    '.'
])

env.AddCflags([
    '-DHAVE_SIGNAL_H'
])

env.Library('cmocka', [
    Glob('src/*.c')
])