__asm__ (".text \n"
".global " START " \n"
".type " START ",%function \n"
START ": \n"
"	mov fp, #0 \n"
"	mov lr, #0 \n"
"	ldr r2, 1f \n"
"	add r2, pc, r2 \n"
"	mov r1, sp \n"
"2:	and ip, r1, #-16 \n"
"	mov sp, ip \n"
"	bl " START "_c \n"
".weak _DYNAMIC \n"
".hidden _DYNAMIC \n"
".align 2 \n"
"1:	.word _DYNAMIC-2b \n"
);
