# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

cflags=' -Ieggs/libgui/ \
        -Ieggs/libjpeg/ \
        -Ieggs/libsdl/ \
        -Ieggs/libsdl/include \
        -I. \
        -Ieggs/libpng/ \
        -Ieggs/libwebp/src \
        '

cflags+='-DSDL_IMAGE_USE_COMMON_BACKEND \
		 -DLOAD_GIF -DLOAD_LBM -DLOAD_PCX -DLOAD_PNM \
		-DLOAD_SVG -DLOAD_TGA  -DLOAD_XPM -DLOAD_XV \
		 -DLOAD_PNG \
         -DFAST_IS_JPEG -DLOAD_WEBP -DLOAD_BMP -DLOAD_XCF -DLOAD_JPG \
        ' #-DNEED_SHORT_EXTERNAL_NAMES   

source=[]

source+=Glob('*.c')

include = [
    '.',
    '../',
    '../include/',
    '../libsdl/include',
    '../libpng',
    '../libwebp/src'
]


libs = [
    'libgui.a',
    'libimage.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
]+env['LIBC']

env.Library('sdl-image', source,
    LIBS=libs+env.get('LIBS'),
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS='$CFLAGS $LIBCFLAGS -DBSD -D__YIYIYA__  '+cflags,
    LINKFLAGS= '$LINKFLAGS $USER')