# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cliEnv')

env=cliEnv

libs=[
 
]+env['LIBC']

libpath=[

]
include=[
    '.',
    '../libs/include/',
    '../include/',
    '../../duck/libs/include'
]+libpath

env.Library('gaga', [
    'client.c',
    ],
    LIBS=libs,
    LIBPATH=env.get('LIBPATH')+libpath,
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS='$CFLAGS ')
