# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c",om
# ********************************************************************
import os

Import('libEnv')
env=libEnv


source = []
source += Glob('src/*.c')


include = [
    'src',
    'include',
    '.',
    '../include'
]

env.Library('lua', source,
            CPPPATH=env.get('CPPPATH')+include,
            CFLAGS='$CFLAGS $LIBCFLAGS')
