# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cliEnv')

env=cliEnv

cflags='-DBSD -D__YIYIYA__  -D__GNUC__ '

include=[
    '../../eggs/libgui',
    '../../eggs/libsdl/include',
    '../../eggs/libsdl/src',
    '../../eggs/libsdl/src/video',
    '../../eggs/libsdl/src/thread',
    '../../eggs/libsdl/src/thread/generic',
    '../../eggs/libsdl/src/timer',
    '../../eggs/libsdl/src/events',
    '../../eggs/libsdl/src/joystick',

    
    '../../eggs/libjpeg/',
    '../../eggs/libfreetype/include',
    'sys/sdl/',
    'include',
    '.',
    '../../eggs/include',
]

libs = [
    'libgui.a',
    'libimage.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
]+env['LIBC']

libpath = [
    '../../eggs/libfreetype',
    '../../eggs/libwebp/',
    '../../eggs/libgui',
    '../../eggs/libimage',
    '../../eggs/libjpeg',
    '../../eggs/libpng',
    '../../eggs/libc/',
    '../../eggs/libzlib',

]


source=[]

source+=Glob('src/*.c')
source+=Glob('src/audio/*.c')
source+=Glob('src/audio/dummy/*.c')
# source+=Glob('src/audio/aaudio/*.c')
# source+=Glob('src/audio/openslES/*.c')
source+=Glob('src/atomic/SDL_atomic.c')
source+=Glob('src/atomic/SDL_spinlock.c')
# source+=Glob('src/core/android/*.c')
source+=Glob('src/cpuinfo/*.c')
# source+=Glob('src/dynapi/*.c')
source+=Glob('src/events/*.c')
source+=Glob('src/file/*.c')
# source+=Glob('src/haptic/*.c')
# source+=Glob('src/haptic/android/*.c')
# source+=Glob('src/hidapi/*.c')
# source+=Glob('src/hidapi/android/*.cpp')
source+=Glob('src/joystick/*.c')
source+=Glob('src/joystick/dummy/*.c')
# source+=Glob('src/joystick/hidapi/*.c')
# source+=Glob('src/joystick/virtual/*.c')
# source+=Glob('src/loadso/dlopen/*.c')
# source+=Glob('src/locale/*.c')
# source+=Glob('src/locale/android/*.c')
# source+=Glob('src/misc/*.c')
# source+=Glob('src/misc/android/*.c')
# source+=Glob('src/power/*.c')
# source+=Glob('src/power/android/*.c')
# source+=Glob('src/filesystem/android/*.c')
# source+=Glob('src/sensor/*.c')
# source+=Glob('src/sensor/android/*.c')
source+=Glob('src/render/*.c')
source+=Glob('src/render/*/*.c')
source+=Glob('src/stdlib/*.c')
source+=Glob('src/libm/*.c')
source+=Glob('src/thread/*.c')
source+=Glob('src/thread/generic/*.c')
# source+=Glob('src/thread/pthread/*.c')
source+=Glob('src/timer/*.c')
source+=Glob('src/timer/yiyiya/*.c')
source+=Glob('src/video/*.c')
source+=Glob('src/video/yiyiya/*.c')
source+=Glob('src/video/yuv2rgb/*.c')




env.Library('sdl', source,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=libpath +env['LIBPATH'],
    CPPPATH=include+ env['CPPPATH'] ,

    CFLAGS= cflags+ '$CFLAGS $LIBCFLAGS  ',
    LINKFLAGS= '$LINKFLAGS $USER')