# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c",om
# ********************************************************************
import os
import sys
import SCons

Import('cliEnv')

env = cliEnv

cflags = ' '

source = []

current = Dir('.').srcnode().path

returns = []

include = ' '.join(map(lambda i: ' -I'+i, env['CPPPATH'])).replace('#', '')
libs = ' '.join(map(lambda i: ' -l'+i, env['LIBS'])).replace('#', '')
libpath = ' '.join(map(lambda i: ' -L'+i, env['LIBPATH'])).replace('#', '')
ldflags = env['LINKFLAGS'] + \
    ' '.join(map(lambda i: '../libmusl/lib/'+i, env['LIBC']))

ldflags += ' '+libpath+' '+libs+' '

cflags += include+' '
cflags += env['CFLAGS']


def patch_path(var):
    var = var.replace(
        'eggs/libmusl', '../libmusl')
    var = var.replace('#../libmusl', '../libmusl')
    return var


params = [
    '--cc='+env['CC'],
    '--ar='+env['AR'],
    '--ranlib='+env['RANLIB'],
    '--enable-cross-compile',
    '--arch='+env['ARCHTYPE'],
    '--target-os=linux',
    # '--cross-prefix='+env['CC_PREFIX'],
    '--extra-cflags=%s  %s %s' % (
        cflags, libpath, libs),
    '--extra-ldflags=%s ' % (ldflags),
    '--host-extralibs=',
    '--enable-gpl',
    '--enable-nonfree',
    '--enable-static',
    '--disable-programs',
    '--disable-stripping',
    '--disable-doc',
    '--disable-pthreads',
    '--disable-shared',
    '--disable-htmlpages',
    '--disable-manpages',
    '--disable-podpages',
    '--disable-txtpages',

    # '--disable-encoders ',
    # '--disable-decoders ',
    # '--enable-decoder=aac',
    # '--enable-decoder=aac_at',
    # '--enable-decoder=h264',
    # '--enable-decoder=h264_mediacodec',
    # '--disable-demuxers ',
    # '--enable-demuxer=aac',
    # '--enable-demuxer=h264',
    '--disable-vfp',
    # '--disable-neon',
    '--disable-inline-asm',


    '--disable-dct',
    '--disable-asm',
    '--disable-network',

    # '--disable-yasm',
    # '--disable-yasm',
    # '--disable-stripping',
    #
    # '--disable-encoders',
    # '--disable-decoders',
    # '--enable-decoder=aac',
    # '--enable-decoder=aac_at',
    # '--enable-decoder=h264',
    # '--enable-decoder=h264_mediacodec',
    # '--disable-demuxers ',
    # '--enable-demuxer=aac',
    # '--enable-demuxer=h264',
]

params = list(map(patch_path, params))


configured = [
    './ffbuild/config.mak'
]

ffmpeg = env.AutoConfig(
    Dir('.'),
    AutoConfigParams=params,
    AutoConfigTarget=configured,
    AutoConfigSource=['configure',
                      '../libmusl/libmusl.a',

                      ]
)



ffmpegMake = env.Make(
    MakePath=Dir('.'),
    source=configured + [
        # Glob('libavdevice/*.c'),
        'Makefile'
    ],
    target=[
        'libavcodec.a',
        'libavdevice.a',
        'libavfilter.a',
        'libavformat.a',
        'libavresample.a',
        'libavutil.a'
    ]
)

env.Clean('ffmpeg',
          ['ffbuild/config.mak',
           Glob('./**/**.[o|a|d]'),
           'config.h',
           'config.asm'
           ])
