# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c",om
# ********************************************************************
import os
import SCons

Import('env')

cflags = ' -L../libmusl/lib '

source = []

current = Dir('.').srcnode().path

returns = []

libpath = ' '.join(map(lambda i: ' -I'+i, env['CPPPATH'])).replace('#/', '')
libs = ''

ldflags = env['LINKFLAGS'] + \
    ' '.join(map(lambda i: '../libmusl/lib/'+i, env['LIBC']))

cflags += env['CFLAGS']


def patch_path(var):
    return var.replace(
        'eggs/libmusl', '../libmusl')


if env.get('MYLIB'):
    ldflags += ' '+env.get('CC_LIB_PATH') + env.get('MYLIB')+' -lm'
    libpath += ' -I'+env.get('CC_LIB_PATH')


def config_build(config=True):
    params = [
        '--enable-cross-compile',
        '--arch='+env['ARCHTYPE'],
        '--target-os=linux',
        '--cross-prefix='+env['CC_PREFIX'],
        '--extra-cflags=%s  %s %s' % (
            libpath, libs, cflags),
        '--extra-ldflags=%s ' % (ldflags),
        '--host-extralibs=',
        '--enable-gpl',
        '--enable-nonfree',
        '--enable-static',
        '--disable-programs',
        '--disable-stripping',
        '--disable-doc',
        '--disable-pthreads',
        '--disable-shared',
        '--disable-htmlpages',
        '--disable-manpages',
        '--disable-podpages',
        '--disable-txtpages',

        # '--disable-encoders ',
        # '--disable-decoders ',
        # '--enable-decoder=aac',
        # '--enable-decoder=aac_at',
        # '--enable-decoder=h264',
        # '--enable-decoder=h264_mediacodec',
        # '--disable-demuxers ',
        # '--enable-demuxer=aac',
        # '--enable-demuxer=h264',
        '--disable-vfp',
        # '--disable-neon',
        '--disable-inline-asm',


        '--disable-dct',
        '--disable-asm',

        # '--disable-yasm',
        # '--disable-yasm',
		# '--disable-stripping',
		# 
		# '--disable-encoders',
		# '--disable-decoders',
		# '--enable-decoder=aac',
		# '--enable-decoder=aac_at',
		# '--enable-decoder=h264',
		# '--enable-decoder=h264_mediacodec',
		# '--disable-demuxers ',
		# '--enable-demuxer=aac',
		# '--enable-demuxer=h264',
    ]

    if config:
        params = map(patch_path, params)

        configured = env.AutoConfig(Dir('.'),
                                    AutoConfigParams=params,
                                    AutoConfigTarget='config.mk',
                                    AutoConfigSource='configure'
                                    )
        env.Command('./ffbuild/config.mak-'+env.get('ARCHTYPE'), configured,
                    'cd %s && make clean && cp ./ffbuild/config.mak ./ffbuild/config.mak-%s' % (current, env.get('ARCHTYPE')))

    else:
        configured = './ffbuild/config.mak-'+env.get('ARCHTYPE'),

    job_number = env.GetOption('num_jobs')
    musl = env.Command('ffmpeg',
                       configured,
                       'cd %s && make -j%d' % (current,job_number))
    env.Requires('ffmpeg','musl')
    
    returns.append(musl)


if os.path.exists('ffbuild/config.mak'):
    print('configure is up-to-date')
    if not os.path.exists('ffbuild/config.mak-'+env.get('ARCHTYPE')):
        print('remove configure')
        os.remove('ffbuild/config.mak')
        config_build()
    else:
        config_build(False)
else:
    config_build()


env.Clean('ffmpeg',['ffbuild/config.mak']+ Glob('./**/**.[o|a]') )


Return('returns')
